source :gemcutter
gem "rails", "2.3.5"
gem "sqlite3-ruby", :require => "sqlite3"
gem "bundler", "0.9.7"
gem "authlogic"
gem "settingslogic"
gem "RedCloth"
gem "thin"
gem "rspec"
gem "rspec-rails"
gem "cucumber"
gem "cucumber-rails"
gem "database_cleaner"
gem "webrat"
gem "selenium-client"
gem "factory_girl"